program: train_imbalanced_classification.py
name: reward_scale_supervised
method: grid
metric:
  goal: minimize
  name: best_eval_dto
parameters:
  train_type:
    value: supervised
  dataset:
    # value: emoji
    value: biasbios
  use_most_common_classes:
    value: False
  random_seed:
    values: [1, 42, 83, 3, 37]
  reward_scale_type:
    values: [imb_ratio_plus, imb_ratio_neg, gender_and_prof]
  num_epoch:
    value: 10
  lr:
    value: 3.0e-4
  batch_size:
    value: 128

