program: train_imbalanced_classification.py
name: final_res_supervised_bios
method: grid
metric:
  goal: minimize
  name: best_eval_dto
parameters:
  train_type:
    value: mp
  dataset:
    # value: emoji
    value: biasbios
  use_most_common_classes:
    values: [False]
  random_seed:
    values: [1, 42, 83, 3, 37]
  reward_scale_type:
    values: [constant]
  num_epoch:
    value: 10
  lr:
    value: 3.0e-4
  batch_size:
    value: 128
  debias_embs:
    value: mp
  debiase_posthoc:
    value: True
