program: train_imbalanced_classification.py
name: sweepdemo_bias_ppo
method: grid
metric:
  goal: minimize
  name: best_eval_dto
parameters:
  train_type:
    value: ppo
  dataset:
    # value: emoji
    value: biasbios
  lr:
    values: [3.0e-4, 1.0e-4, 3.0e-5, 1.0e-5, 3.0e-6, 1.0e-6]
  critic_lr:
    values: [1.0e-3, 3.0e-4, 1.0e-4, 3.0e-5, 1.0e-5]
  eps_clip:
    # values: [0.1, 0.2] 
    value: 0.1
  entropy_coef:
    value: 0.1 
  batch_size:
    value: 512

