program: train_imbalanced_classification.py
name: sweepdemo_emoji_ppo
method: bayes
metric:
  goal: minimize
  name: best_eval_dto
parameters:
  train_type:
    value: ppo
  dataset:
    value: emoji
    # value: biasbios
  lr:
    values: [3.0e-4, 1.0e-4, 3.0e-5, 1.0e-5, 3.0e-6, 1.0e-6]
  critic_lr:
    values: [1.0e-3, 3.0e-4, 1.0e-4, 3.0e-5, 1.0e-5]
  eps_clip:
    values: [0.05, 0.1, 0.2, 0.3] 
  entropy_coef:
    values: [0.01, 0.05, 0.1] 
  batch_size:
    values: [128, 256, 512]

