program: train_imbalanced_classification.py
name: sweepdemo_emoji
method: bayes
metric:
  goal: minimize
  name: best_eval_dto
parameters:
  train_type:
    values: [ppo]
  dataset:
    values: [emoji]
    # dataset: [biasbios]
  lr:
    values: [3.0e-4, 1.0e-4, 3.0e-5, 1.0e-5, 3.0e-6, 1.0e-6]
    # distribution: log_uniform_values
    # min: 1.0e-6
    # max: 3.0e-4
  critic_lr:
    # distribution: log_uniform_values
    values: [1.0e-3, 3.0e-4, 1.0e-4, 3.0e-5, 1.0e-5]
    # min: 1.0e-5
    # max: 1.0e-3
  eps_clip:
    values: [0.05, 0.1, 0.2, 0.3] 
    # probabilties: [0.1, 0.2, 0.5, 0.2]
  entropy_coef:
    values: [0.01, 0.05, 0.1] 
    # probabilities: [0.2, 0.6, 0.2]
  batch_size:
    values: [128, 256, 512]

