program: train_imbalanced_classification.py
name: sweepdemo_supervised_emoji
method: bayes
metric:
  goal: minimize
  name: best_eval_dto
parameters:
  train_type:
    value: supervised
  dataset:
    value: emoji
    # value: biasbios
  reward_scale_type:
    value: EO
  lr:
    values: [1.0e-3, 3.0e-4, 1.0e-4, 3.0e-5, 1.0e-5, 3.0e-6, 1.0e-6]
  batch_size:
    values: [64, 128, 256, 512]
